
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoginProvider from "@/context/LoginContext";
import HomeScreen from '@/components/HomeScreen';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="pt-br">
      <LoginProvider>
        <body className={inter.className}>
          <HomeScreen>
            {children}
          </HomeScreen>
        </body>
      </LoginProvider>
    </html>
  );
}
